job: extension
config:
  name: model_A_lora_v1
  process:
  - type: sd_trainer
    training_folder: model_A_output
    performance_log_every: 100
    device: cuda:0
    trigger_word: model_A
    network:
      type: lora
      linear: 64
      linear_alpha: 64
    save:
      dtype: float16
      save_every: 100
      max_step_saves_to_keep: 30
    datasets:
    - folder_path: model_A
      caption_ext: txt
      caption_dropout_rate: 0.005
      shuffle_tokens: false
      cache_latents_to_disk: true
      resolution:
      - 768
      - 1024
    train:
      batch_size: 8
      steps: 3000
      gradient_accumulation_steps: 1
      train_unet: true
      train_text_encoder: false
      content_or_style: balanced
      gradient_checkpointing: true
      noise_scheduler: flowmatch
      optimizer: adamw8bit
      lr: 0.0003
      lr_scheduler: cosine
      scheduler_params:
        T_max: 3000
        eta_min: 5.0e-05
      ema_config:
        use_ema: true
        ema_decay: 0.99
      dtype: bf16
    model:
      name_or_path: black-forest-labs/FLUX.1-dev
      is_flux: true
      quantize: true
    sample:
      sampler: flowmatch
      sample_every: 100
      width: 768
      height: 768
      prompts:
      - A portrait of male model model_A wearing a red sweater.
      - A male model, model_A, sits with a poised and relaxed demeanor, one arm resting
        on the chairs arm, dressed in a sleek dark suit paired with a crisp white
        shirt.
      neg: ''
      seed: 42
      walk_seed: true
      guidance_scale: 4
      sample_steps: 20
meta:
  name: model_A_lora_v1
  version: '1.0'
